---
- name: Setup and format drive
  hosts: localhost
  connection: local
  become: true
#  vars_prompt:
#    - name: loadkeys
#      prompt: Which loadkeys to use
#      private: no
#    - name: device
#      prompt: Which device to install?
#      private: no
#    - name: passphrase
#      prompt: Passphrase for LUKS partition?
  vars:
    device: /dev/nvme0n1
    loadkeys: se-lat6
    passphrase: xxxxx
    hostname: burk
    locale: |
      en_GB.UTF-8 UTF-8
      sv_SE.UTF-8 UTF-8
  tasks:
#    - name: loadkeys {{ loadkeys }}
#      become: true
#      ansible.builtin.command: "loadkeys {{ loadkeys }}"
#
#    - name: enable systemd-timesyncd
#      ansible.builtin.service:
#        name: systemd-timesyncd
#        state: started
#        enabled: true
#
#    - name: set stable pacman-mirrors with --geoip
#      become: true
#      ansible.builtin.command: pacman-mirrors --set-branch stable --api --geoip
#
    - name: update keyring and install base tools
      community.general.pacman:
        name:
          - archlinux-keyring
          - manjaro-keyring
          - manjaro-tools-base-git
        state: present
        update_cache: yes
#
#    - name: pacman-key init
#      ansible.builtin.command: pacman-key --init
#
#    - name: pacman-key populate
#      ansible.builtin.command: pacman-key --populate archlinux manjaro
#
#    - name: pacman-key refresh
#      ansible.builtin.command: pacman-key --refresh-keys

    - name: create boot partition
      community.general.parted:
        device: "{{ device }}"
        number: 1
        label: gpt
        name: EFI system partition
        state: present
        flags: [ esp ]
        part_start: "0%"
        part_end: "512MiB"

    - name: create fat32 filesystem on boot partition
      community.general.filesystem:
        fstype: vfat
        opts: "-F 32"
        dev: "{{ device }}p1"

    - name: create primary partition
      community.general.parted:
        device: "{{ device }}"
        number: 2
        label: gpt
        name: root
        state: present
        part_start: 512MiB
        part_end: 100%

    - name: create LUKS container with a passphrase
      community.crypto.luks_device:
        device: "{{ device }}p2"
        state: opened
        name: cryptoroot
        passphrase: "{{ passphrase }}"

#    - name: open LUKS container with a passphrase
#      community.crypto.luks_device:
#        device: "{{ device }}p2"
#        state: opened
#        name: cryptroot
#        passphrase: "{{ passphrase }}"

    - name: create a ext4 filesystem on cryptoroot
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/mapper/cryptoroot"
#        opts: -cc

    - name: mount root to /mnt
      ansible.posix.mount:
        path: /mnt
        src: "/dev/mapper/cryptoroot"
        fstab: /tmp/test_fstab
        fstype: ext4
        state: mounted
        opts: rw,noatime

    - name: mount EFI to /mnt/boot/efi
      ansible.posix.mount:
        path: /mnt/boot/efi
        src: "{{ device }}p1"
        fstab: /tmp/test_fstab
        fstype: vfat
        state: mounted

    - name: basestrap /mnt
      ansible.builtin.command: basestrap /mnt base linux510 linux-firmware vim networkmanager git ansible dhcp

    - name: fstabgen
      ansible.builtin.command: bash -c 'fstabgen -U /mnt >> /mnt/etc/fstab'

    - name: set localtime to Europe/Stockholm
      ansible.builtin.command: manjaro-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime

    - name: hwclock --systohc
      ansible.builtin.command: manjaro-chroot /mnt hwclock --systohc

    - name: set-local
      ansible.builtin.copy:
        content: '{{ locale }}'
        dest: /mnt/etc/locale.gen

    - name: locale-gen
      ansible.builtin.command: manjaro-chroot /mnt locale-gen

    - name: set a hostname
      ansible.builtin.copy:
        dest: /mnt/etc/hostname
        content: "{{ hostname }}"

    - name: install grub
      ansible.builtin.command: manjaro-chroot /mnt pacman -S --noconfirm grub efibootmgr

    - name: run grub-install
      ansible.builtin.command: manjaro-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=manjaro --recheck

    - name: update-grub
      ansible.builtin.command: manjaro-chroot /mnt update-grub


#    - name: run install
#      ansible.builtin.command: ansible-playbook -c manjaro-chroot {{ ans_root }}/install.yml #--skip-tags "handlers"
#TOOD
# 1. bash -c 'fstabgen /mnt >> /mnt/etc/fstab'
# 2. script for chroot
# 2.1 
#https://amaikinono.github.io/install-minimal-manjaro.html
#https://wiki.archlinux.org/title/installation_guide#Installation
#