---
- name: Install new drive
  hosts: localhost
  connection: local
  become: true
  vars:
#    device: /dev/nvme0n1
#    loadkeys: se-lat6
  tasks:
    - name: set localtime to Europe/Stockholm
      ansible.builtin.command: manjaro-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime

    - name: hwclock --systohc
      connection: local
      ansible.builtin.command: manjaro-chroot /mnt hwclock --systohc

    - name: set-local
      become: true
      ansible.builtin.copy:
        content: '{{ locale }}'
        dest: /mnt/etc/locale.gen

    - name: locale-gen
      become: true
      ansible.builtin.command: manjaro-chroot /mnt locale-gen

    - name: set a hostname
      ansible.builtin.copy:
        dest: /mnt/etc/hostname
        content: "{{ hostname }}"

    - name: install grub
      ansible.builtin.command: manjaro-chroot /mnt pacman -S --noconfirm grub efibootmgr

    - name: run grub-install
      ansible.builtin.command: manjaro-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=manjaro --recheck

    - name: update-grub
      ansible.builtin.command: manjaro-chroot /mnt update-grub
#
#    - name: set-local
#      become: true
#      ansible.builtin.copy:
#        content: '{{ locale }}'
#        dest: /mnt/etc/locale.gen
#
#    - name: locale-gen
#      become: true
#      ansible.builtin.command: manjaro-chroot /mnt locale-gen
#                                 - name: Ensure a locale exists
#                                 community.general.locale_gen:
#                                   name: de_CH.UTF-8
#                                   state: present
