---
roles:
  - name: kewlfft.aur
    version: v0.43
  - name: cloudalchemy.node_exporter
    version: 2.0.0

collections:
#   Install a collection from Ansible Galaxy.
#  - name: geerlingguy.php_roles
#    version: 0.9.3
#    source: https://galaxy.ansible.com