- name: Install core packages
  become: true
  community.general.pacman:
    name:
      - arandr
      - bind
      - blueman
      - bluez
      - clamav
      - dmidecode
      - docker
      - gnu-netcat
      - htop
      - iotop
      - inetutils
      - jq
      - hey
      - man-db
      - ncdu
      - net-tools
      - network-manager-applet
      - networkmanager
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - ntp
      - openssh
      - pciutils
      - pwgen
      - python
      - rsync
      - sshpass
      - tcpdump
      - ttf-jetbrains-mono
      - unzip
  tags: core

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present
  tags: core

- name: Add ansible_env.USER to docker
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  tags: core

- name: Set locale
  become: true
  community.general.locale_gen:
    name: sv_SE.UTF-8
    state: present
  tags: core

- name: start core services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - NetworkManager
    - clamav-daemon
    - clamav-freshclam
    - docker
    - ntpd
  tags: core