- name: Install core packages
  become: true
  community.general.pacman:
    name:
      - arandr
      - bind
      - clamav
      - docker
      - gnu-netcat
      - iotop
      - htop
      - man-db
      - ncdu
      - network-manager-applet
      - networkmanager
      - net-tools
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - openssh
      - pciutils
      - pwgen
      - tcpdump
      - ttf-jetbrains-mono
      - etcher
      - ntp
      - unzip
      - sshpass
  tags: core

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present
  tags: core

- name: Add ansible_env.USER to docker
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  tags: core

- name: start core services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - NetworkManager
    - clamav-daemon
    - clamav-freshclam
    - docker
    - ntpd
  tags: core

# - name: localectl
#   community.general.locale_gen:
#     name: "{{ item }}"
#     state: present
#   with_items:
#    - "en_GB.UTF-8"
#    - "sv_SE.UTF-8"
#   tags: core