- name: "copy git directory for hooks and ignore"
  ansible.builtin.copy:
    src: "files/git"
    dest: "{{ ansible_env.HOME }}"
  tags: git

- name: "Copy .gitconfig"
  ansible.builtin.template:
    src: ".gitconfig.j2"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  tags: git