- name: Install i3 packages
  become: true
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xev
      - xfce4-notifyd
      - i3-wm
      - i3status
      - i3blocks
      - xautolock
      - dmenu
      - xdotool
      - yad
      - sysstat
      - gnome-screenshot
  tags: i3

- name: Install i3 packages
  kewlfft.aur.aur:
    name:
      - i3lock-color-git
  tags: i3

- name: "Ensure fontconfig dir exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
  tags: i3

- name: "Copy .xinitrc, .Xresources and i3 config"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
    - ".xinitrc"
    - ".Xresources"
    - ".config/i3/config"
  tags: i3

- name: "Copy etc/X11/xorg.conf"
  become: true
  ansible.builtin.copy:
    content: "{{ etc_X11_xorg_conf }}"
    dest: "/etc/X11/xorg.conf"
  tags: i3
  when: etc_X11_xorg_conf | length > 0

- name: "set XkbLayout se"
  become: true
  ansible.builtin.copy:
    content: |
          # Written by systemd-localed(8), read by systemd-localed and Xorg. It's
          # probably wise not to edit this file manually. Use localectl(1) to
          # instruct systemd-localed to update it.
          Section "InputClass"
            Identifier "system-keyboard"
            MatchIsKeyboard "on"
            Option "XkbLayout" "se"
          EndSection

    dest: "/etc/X11/xorg.conf.d/00-keyboard.conf"
  tags: i3

#TODO add current net bandwidth usage, current io usage in mb
- name: "Copy i3blocks"
  ansible.builtin.copy:
    src: "files/i3blocks"
    mode: a+x
    dest: "{{ ansible_env.HOME }}/.config"
  tags: i3
