
- name: pre_load vars based on hostname
  ansible.builtin.include_vars:
    file: "{{ ansible_hostname }}.yml"
  tags: always

- include_tasks: core.yml
  tags: core

- include_tasks: bash.yml
  tags: bash

- include_tasks: git.yml
  tags: git

- include_tasks: i3.yml
  tags: i3

- include_tasks: audio.yml
  tags: audio

- include_tasks: code.yml
  tags: code

- name: Install additional packages pacman
  become: true
  community.general.pacman:
    name: "{{ additionalPackages }}"
  when: additionalPackages | length > 0

- name: Install additional packages aur
  kewlfft.aur.aur:
    name: "{{ additionalPackagesAur }}"
  when: additionalPackagesAur | length > 0

- name: Install additional packages snap
  become: true
  community.general.snap:
    name: "{{ additionalPackagesSnap }}"
    classic: true
  when: additionalPackagesSnap | length > 0

- name: Install additional packages apt
  become: true
  ansible.builtin.apt:
    name: "{{ additionalPackagesApt }}"
  when: additionalPackagesApt | length > 0
