additionalPackages:

#additionalPackagesAur:

git_config_name: "Fabian Heib"
git_config_email: "11271952+xonvanetta@users.noreply.github.com"
git_config_username: "xonvanetta"
git_config_extra: |
  [url "git@gitlab.com:"]
  	insteadOf = https://gitlab.com/

bash_alias_extra: |
  alias updatekubeconfig="KUBECONFIG=$(find ~/.kube/configs/ -type f | tr '\n' ':') kubectl config view --merge --flatten > ~/.kube/config"