start_options: "xrandr --output HDMI-A-0 --rate 144 --mode 2560x1440 --pos 2560x0 --rotate normal --primary --output DisplayPort-2 --mode 2560x1440 --pos 0x0 --rotate normal --output DisplayPort-3 --off"

additionalPackages:
  - steam-manjaro
  - lib32-libnm #https://github.com/ValveSoftware/steam-for-linux/issues/9805
  - xdg-user-dirs
  - discord
  - teamspeak3
# https://github.com/lutris/docs/blob/master/InstallingDrivers.md
  - vulkan-radeon
  - lib32-vulkan-radeon
  - lib32-mesa
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - xf86-video-amdgpu

additionalPackagesAur:
  - spotify
  - obs-ndi
 # systemctl status avahi-daemon.service
  - proton-ge-custom-bin

git_config_name: "Vanetta"
git_config_email: "11271952+xonvanetta@users.noreply.github.com"
git_config_username: "xonvanetta"
git_config_extra: |
  [url "git@gitlab.com:"]
  	insteadOf = https://gitlab.com/

bash_alias_extra: |
  alias updatekubeconfig="KUBECONFIG=$(find ~/.kube/configs/ -type f | tr '\n' ':') kubectl config view --merge --flatten > ~/.kube/config"