xrandr_start_options: "--output HDMI-0 --rate 144 --mode 2560x1440 --pos 2560x0 --rotate normal --primary --output DP-4.8 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-4.1 --off"

additionalPackages:
  - linux510-nvidia
  - steam-manjaro
  - discord
  - teamspeak3
# https://github.com/lutris/docs/blob/master/InstallingDrivers.md
# $ sudo pacman -S --needed nvidia-dkms nvidia-utils lib32-nvidia-utils vulkan-icd-loader lib32-vulkan-icd-loader
  - obs-studio
  - sndio
  - nvidia-dkms
  - nvidia-utils
  - lib32-nvidia-utils
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader

additionalPackagesAur:
  - spotify
  - obs-ndi
 # systemctl status avahi-daemon.service
  - proton-ge-custom-bin

git_config_name: "Vanetta"
git_config_email: "11271952+xonvanetta@users.noreply.github.com"
git_config_username: "xonvanetta"
git_config_extra: |
  [url "git@gitlab.com:"]
  	insteadOf = https://gitlab.com/


bash_profile_extra: |
  export __GL_SYNC_TO_VBLANK=1
  export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
  export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0

etc_X11_xorg_conf: |
  # nvidia-settings: X configuration file generated by nvidia-settings
  # nvidia-settings:  version 470.63.01

  Section "ServerLayout"
      Identifier     "Layout0"
      Screen      0  "Screen0" 0 0
      InputDevice    "Keyboard0" "CoreKeyboard"
      InputDevice    "Mouse0" "CorePointer"
      Option         "Xinerama" "0"
  EndSection

  Section "Files"
  EndSection

  Section "InputDevice"
      # generated from default
      Identifier     "Mouse0"
      Driver         "mouse"
      Option         "Protocol" "auto"
      Option         "Device" "/dev/psaux"
      Option         "Emulate3Buttons" "no"
      Option         "ZAxisMapping" "4 5"
  EndSection

  Section "InputDevice"
      # generated from default
      Identifier     "Keyboard0"
      Driver         "kbd"
  EndSection

  Section "Monitor"
      # HorizSync source: edid, VertRefresh source: edid
      Identifier     "Monitor0"
      VendorName     "Unknown"
      ModelName      "Acer XV272U V"
      HorizSync       30.0 - 230.0
      VertRefresh     48.0 - 144.0
      Option         "DPMS"
  EndSection

  Section "Device"
      Identifier     "Device0"
      Driver         "nvidia"
      VendorName     "NVIDIA Corporation"
      BoardName      "NVIDIA GeForce GTX 1070 Ti"
  EndSection

  Section "Screen"
      Identifier     "Screen0"
      Device         "Device0"
      Monitor        "Monitor0"
      DefaultDepth    24
      Option         "Stereo" "0"
      Option         "nvidiaXineramaInfoOrder" "DFP-1"
      Option         "metamodes" "HDMI-0: 2560x1440_144 +2178+0, DP-4.8: nvidia-auto-select +0+0"
      Option         "SLI" "Off"
      Option         "MultiGPU" "Off"
      Option         "BaseMosaic" "off"
      SubSection     "Display"
          Depth       24
      EndSubSection
  EndSection