#!/usr/bin/python
# -*- coding: utf-8 -*-

from openrazer.client import DeviceManager

device_manager = DeviceManager()

d = None
for device in device_manager.devices:
    if "Razer Naga V2 HyperSpeed (Receiver)" == device.name:
        d = device
        break

if d is None:
    print("n/a")
    exit(1)

print(" {}%".format(d.battery_level))
