xrandr_start_options: ""

git_config_name: ""
git_config_email: ""
git_config_username: ""
git_config_extra: ""

additionalPackages: []
additionalPackagesAur: []
additionalGoInstalls: []

bash_profile_extra: ""
bash_rc_completion_extra: ""
bash_alias_extra: ""

etc_X11_xorg_conf: ""
